Use first image (after refactor)
wpilibsuite/sphinxext-opengraph pull request #26
Opened 2020-10-03 07:32 UTC by TheTripleV

This PR is functionally the same as the description in #18 but is applied after the refactor.

2020-10-04 02:05 UTC, tcmetzger commented
Absolutely - just give me few days!

2020-10-08 21:23 UTC, tcmetzger commented
One small thing I noticed right away: in readme.md, line 16, there should be quotation marks around `sphinxext.opengraph` (should be a list of strings).

2020-10-08 21:37 UTC, tcmetzger commented on sphinxext/opengraph/__init__.py
> +        if Path(first_image.get("uri", "")).suffix[1:].lower() in IMAGE_MIME_TYPES:
I believe this line throws an error (`'NoneType' object has no attribute 'get'`) under the following conditions:
* `ogp_use_first_image ` is set to True in conf.py.
* there is a .rst file that does not include any images.

According to README.md, the expected behaviour in a case like this is to use `ogp_image`.

2020-10-08 21:58 UTC, tcmetzger commented
Those two issues are the only two things I was able to see. 
Thanks for your work on this very helpful extension!

2020-10-08 22:07 UTC, tcmetzger requested changes
Changes I recommend:
* add quotation marks to README.md, line 16
* handle a situation where `ogp_use_first_image` is enabled but no image is present

2020-10-09 05:08 UTC, TheTripleV commented
I addressed the 2 issues and added a test case to cover

> situation where ogp_use_first_image is enabled but no image is present

2020-10-09 17:42 UTC, tcmetzger approved these changes
LGTM!

2020-10-17 17:16 UTC, Daltz333 approved these changes

2020-10-17 17:16 UTC, merged