Implement RTD Support
wpilibsuite/sphinxext-opengraph pull request #30
Opened 2020-12-20 21:51 UTC by Daltz333

2021-01-26 05:30 UTC, TheTripleV requested changes

2021-01-26 05:30 UTC, TheTripleV commented on README.md
> +Users hosting documentation *do not* need to set any of the following unless custom configuration is wanted. The extension will automatically retrieve your site url.
Mention that autopopulation only occurs on Readthedocs.

2021-01-26 06:02 UTC, TheTripleV commented
Ooh thanks for reminding me of test cases.

For test cases:
You can set environment variables with https://docs.pytest.org/en/stable/monkeypatch.html#monkeypatching-environment-variables:~:text=behavior.%22%22%22-,monkeypatch.setenv(%22USER%22%2C%20%22TestingUser%22)
You can probably set html_baseurl and needed rtd vars in conf.py of each test root.

It would be nice if you could include test cases for:
- [ ] RTD ENV is set & html_baseurl is set
- [ ] RTD ENV is set & html_baseurl is NOT set
- [ ] RTD ENV is set & ogp_site_url is set

2021-01-28 08:17 UTC, Modelmat commented on tests/conftest.py
> +def set_config_options(app: Sphinx, config: dict) -> None:
You don't actually end up using this.

2021-01-28 08:20 UTC, TheTripleV commented
Fixed the tests (kinda).
```py
urlparse(config["html_baseurl"])
```
doesn't return None; It returns a parse object.

All 3 of the tests pass when run individually but don't work when run together.

2021-01-30 02:46 UTC, TheTripleV approved these changes

2021-01-30 02:49 UTC, merged